id: ACACCCCED
base_file: f8A98.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-05-30 22:00:48.011215
  last_modified_at: 2022-05-30 22:00:48.011225
